# Generated by Django 4.1 on 2022-10-04 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_order_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
